web:
  image: nginx
  restart: always
  volumes:
   - ./templates:/etc/nginx/templates
   - ./personal-website-angular:/usr/share/nginx/html
  ports:
   - "6868:80"
  environment:
   - NGINX_HOST=foobar.com
   - NGINX_PORT=80
